dolthub/dolthub-cypress

- cypress/integration/productionTests/publicPaths/render/diffs/coronaDiffCommitsNotVisible.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsDiffNoChanges.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsDiffNoSelectedCommits.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsOneSelectedCommit.spec.ts
- cypress/integration/productionTests/publicPaths/render/pull/coronaMergedPull.spec.ts
- cypress/integration/utils/devices.ts
Goes with https://github.com/liquidata-inc/ld/pull/4930
> cypress/integration: Add more diff tests and skip navbar temporarily for merged pull page tests

- cypress/integration/utils/devices.ts
- cypress/integration/utils/sharedTests/navbar.ts
Update tests for new navbar in https://github.com/liquidata-inc/ld/pull/4972
> cypress/integration/utils: Update navbar tests

- .github/workflows/tests.yaml
- .gitignore
- cypress/integration/productionTests/privatePaths/render/profile/index.spec.ts
- cypress/integration/productionTests/publicPaths/render/pull/coronaMergedPull.spec.ts
- cypress/integration/productionTests/publicPaths/render/signin/login.spec.ts
- cypress/integration/utils/helpers.ts
- cypress/integration/utils/index.ts
- cypress/integration/utils/types.ts
- cypress/support/commands.ts
- cypress/support/global.d.ts
- package.json
Can be run locally with dolthub branch https://github.com/dolthub/ld/pull/5166 (now deployed)
Progress on #1
> Start supporting dolthub login

- cypress/integration/productionTests/publicPaths/render/repository/corona-virus.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/forked.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/ngrams.spec.ts
- cypress/integration/utils/sharedTests/pagination.ts
> Add tests for data table pagination

- cypress/integration/productionTests/privatePaths/render/repository/empty.spec.ts
- cypress/integration/productionTests/privatePaths/render/repository/emptyWithBranch.spec.ts
- cypress/integration/productionTests/privatePaths/render/repository/tablesAndDocs.spec.ts
- cypress/integration/productionTests/privatePaths/render/upload/empty.spec.ts
- cypress/integration/productionTests/privatePaths/render/upload/index.spec.ts
- cypress/integration/utils/devices.ts
- cypress/integration/utils/sharedTests/repoLeftNav.ts
Goes with dolthub changes https://github.com/dolthub/ld/pull/5407 (currently deployed to dev)
> Add cypress tests for logged in repo page and basic upload page tests

- cypress/integration/productionTests/privatePaths/render/webhooks/index.spec.ts
- cypress/integration/productionTests/privatePaths/render/webhooks/noWebhooks.spec.ts
- cypress/integration/productionTests/privatePaths/render/webhooks/webhook.spec.ts
- cypress/integration/productionTests/publicPaths/render/webhooks/index.spec.ts
Needs https://github.com/dolthub/ld/pull/5737 in prod to pass
> Add tests for webhooks pages

- cypress/integration/productionTests/privatePaths/render/repository/empty.spec.ts
- cypress/integration/productionTests/privatePaths/render/repository/emptyWithBranch.spec.ts
- cypress/integration/productionTests/privatePaths/render/repository/tablesAndDocs.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/corona-virus.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/docsNoTables.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/empty.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/emptyWithBranch.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/forked.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/ngrams.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/tablesAndDocs.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/tablesNoDocs.spec.ts
- cypress/integration/productionTests/publicPaths/render/repository/tags.spec.ts
- cypress/integration/utils/sharedTests/repoLeftNav.ts
Did a better job testing all the repo pages locally this time and they're all passing
> Handle about sections test for different repos

- cypress/integration/productionTests/publicPaths/render/homepage/index.spec.ts
Will unskip when they're updated for new homepage
> Skip homepage tests

- .github/workflows/tests.yaml
- cypress.json
- cypress/integration/productionTests/privatePaths/render/awarmup/index.spec.ts
- cypress/integration/productionTests/privatePaths/render/profile/discover.spec.ts
- cypress/integration/productionTests/privatePaths/render/profile/index.spec.ts
- cypress/integration/productionTests/privatePaths/render/profile/organizations.spec.ts
- cypress/integration/productionTests/privatePaths/render/profile/starred.spec.ts
- cypress/integration/productionTests/privatePaths/render/repository/empty.spec.ts
- cypress/integration/productionTests/privatePaths/render/repository/emptyWithBranch.spec.ts
- cypress/integration/productionTests/privatePaths/render/settings/index.spec.ts
- cypress/integration/productionTests/publicPaths/render/discover/withQuery.spec.ts
- cypress/integration/productionTests/publicPaths/render/signin/redirects.spec.ts
- cypress/support/commands.ts
- cypress/support/global.d.ts
- package.json
Reference for waiting for page: https://www.cypress.io/blog/2018/02/05/when-can-the-test-start/
> Fix signin for private paths

- cypress/integration/productionTests/publicPaths/render/blog/article.spec.ts
- cypress/integration/productionTests/publicPaths/render/blog/index.spec.ts
- cypress/integration/productionTests/publicPaths/render/discover/index.spec.ts
- cypress/integration/productionTests/publicPaths/render/discover/withQuery.spec.ts
- cypress/integration/utils/sharedTests/sidecar.ts
Goes with https://github.com/dolthub/ld/pull/6716
> Update blog tests for new design

- cypress/integration/productionTests/publicPaths/render/diffs/coronaDiffCommitsNotVisible.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsDiffNoChanges.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsDiffNoSelectedCommits.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsDiffWithChanges.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsOneSelectedCommit.spec.ts
- cypress/integration/productionTests/publicPaths/render/pull/coronaMergedPull.spec.ts
- cypress/integration/productionTests/publicPaths/render/pull/coronaMergedPullDiff.spec.ts
- cypress/integration/productionTests/publicPaths/render/pull/coronaMergedPullDiffRange.spec.ts
- cypress/integration/productionTests/publicPaths/render/pull/coronaOpenPull.spec.ts
- cypress/integration/productionTests/publicPaths/render/pull/coronaOpenPullDiff.spec.ts
- cypress/integration/productionTests/publicPaths/render/pull/coronaOpenPullDiffRange.spec.ts
Dolthub PR:  https://github.com/dolthub/ld/pull/6996
> New pull and diff tests

- cypress/integration/productionTests/privatePaths/render/settings/billing.spec.ts
- cypress/integration/productionTests/privatePaths/render/settings/credentials.spec.ts
- cypress/integration/productionTests/privatePaths/render/settings/databases.spec.ts
- cypress/integration/productionTests/privatePaths/render/settings/email.spec.ts
- cypress/integration/productionTests/privatePaths/render/settings/organizations.spec.ts
- cypress/integration/productionTests/privatePaths/render/settings/security.spec.ts
Should there be more tests for databases? I feel like there should be, but also that maybe it's tested somewhere else
> Kathleen settings email

- cypress/integration/productionTests/publicPaths/render/blog/index.spec.ts
- cypress/integration/productionTests/publicPaths/render/blog/query.spec.ts
- cypress/integration/utils/helpers.ts
- cypress/integration/utils/sharedTests/blog.ts
Tests for https://github.com/dolthub/dolthub-issues/issues/115 bc I keep breaking the blog
> Add tests for blog search/pagination

- README.md
- cypress/integration/productionTests/privatePaths/render/workspaces/index.spec.ts
Deployed a dolthub change that broke a cypress test for workspaces
> Fix workspace test that checks for commit message textarea

- cypress/integration/utils/sharedTests/footer.ts
This link wasn't going anywhere new so removed from the footer
> Remove solutions link from footer tests

- cypress/integration/productionTests/publicPaths/render/diffs/coronaDiffOlderCommit.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsDiffNoChanges.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsDiffNoSelectedCommits.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsDiffRangeWithChanges.spec.ts
- cypress/integration/productionTests/publicPaths/render/diffs/ngramsOneSelectedCommit.spec.ts
- cypress/integration/utils/sharedTests/diffs.ts
Goes with https://github.com/dolthub/ld/pull/8505
> Tests for commit info component

- cypress/integration/productionTests/publicPaths/render/database/ngrams.spec.ts
Added a newExpectation that the data table should be there, helped with flakeyness locally
> Flakey ngram ipad test

- cypress/integration/dolthub/productionTests/publicPaths/render/discover/repositoriesWithQuery.spec.ts
- cypress/integration/utils/sharedTests/reposContainer.ts
Needs changes from https://github.com/dolthub/ld/pull/8777 to pass
> Add test for discover with query param and pagination

- cypress/integration/dolthub/productionTests/publicPaths/render/pulls/index.spec.ts
skip iPhone test for pulls page, wait for mobile tests.
> pulls page fix

- cypress/integration/dolthub/productionTests/publicPaths/render/commits/index.spec.ts
to fix desktop tests because of recent changes
> commit log test

- cypress/integration/dolthub/productionTests/publicPaths/render/discover/withQuery.spec.ts
- cypress/integration/utils/sharedTests/reposContainer.ts
moved clear search tests to utils in case we will add it back in the future
> skip-flaky-search-test

- cypress/e2e/dolthub/privatePaths/render/organizations/index.spec.ts
- cypress/e2e/dolthub/privatePaths/render/users/index.spec.ts
- cypress/e2e/dolthub/publicPaths/render/organizations/billing.spec.ts
- cypress/e2e/dolthub/publicPaths/render/organizations/index.spec.ts
- cypress/e2e/dolthub/publicPaths/render/organizations/noRepos.spec.ts
- cypress/e2e/dolthub/publicPaths/render/organizations/paymentHistory.spec.ts
- cypress/e2e/dolthub/publicPaths/render/organizations/settings.spec.ts
- cypress/e2e/dolthub/publicPaths/render/users/index.spec.ts
Cleaned these up a lot too to make them easier to read/shorter
> Fix org/user profile tests

- .gitignore
- cypress/e2e/dolthub/publicPaths/render/blog/index.spec.ts
- cypress/e2e/dolthub/publicPaths/render/blog/query.spec.ts
two results were showing up for the figma query now that the whole blog is search indexed
> Fix blog search tests
